<a href="https://colab.research.google.com/github/DJKIMM/assignment_stat.math/blob/main/2053001_%EA%B9%80%EB%8B%A4%EC%A0%95_python5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python problem 1: 
## Write  python  function  to  calculate  the  inner  product  using  matrix  multiplication where  inputs  are  Numpy  column  vectors $u$ and $v$.  Then,  try  you  function  with Problem 6 in Chapter 4

In [ ]:
import numpy as np

##Answer

In [ ]:
def inner(u, v): # 매개변수 u, v는 column vector
  return u.T @ v

### 결과값 확인

In [ ]:
# 6 - (1)
u = np.array([-1, 3]).T
v = np.array([2, 4]).T
print(inner(u, v))

10


In [ ]:
# 6 - (2)
u = np.array([-1, 1, 4]).T
v = np.array([3, 2, -2]).T
print(inner(u, v))

-9


In [ ]:
# 6 - (3)
u = np.array([1, -1, 1, 4]).T
v = np.array([1, 1, 2, -2]).T
print(inner(u, v))

-6


In [ ]:
# 6 - (4)
u = np.array([-1, 1, 2, 4]).T
v = np.array([1, 0, 2, -2]).T
print(inner(u, v))

-5


#Python problem 2:
##Use “numpy.inner” to calculate the inner product where inputs are Numpy vectors $u$ and $v$. Then, try you function with Problem 6 in Chapter 4. 

In [ ]:
import numpy as np

In [ ]:
# 6 - (1)
u = np.array([-1, 3]).T
v = np.array([2, 4]).T
np.inner(u, v)

10

In [ ]:
# 6 - (2)
u = np.array([-1, 1, 4]).T
v = np.array([3, 2, -2]).T
np.inner(u, v)

-9

In [ ]:
# 6 - (3)
u = np.array([1, -1, 1, 4]).T
v = np.array([1, 1, 2, -2]).T
np.inner(u, v)

-6

In [ ]:
# 6 - (4)
u = np.array([-1, 1, 2, 4]).T
v = np.array([1, 0, 2, -2]).T
np.inner(u, v)

-5

# Python problem 3: 
## Write python function to return the unit length vector from the input Numpy vectors $u$. (Here, $u$ is assumed to be a non-zero vecto.) Specifically, your return should be $1/||u|| * u$

In [ ]:
def unit(u): # 매개변수는 vector u
  return 1/(np.sqrt(np.inner(u, u))) * u

In [ ]:
# 확인
v = np.array([-1, 3])
print(unit(v))

[-0.31622777  0.9486833 ]


# Python problem 4.
## In $R^3$, you want to calculate orthogonal projection of $a = (a_1, a_2, a_3)$ in $R^3$ onto $W = <(u_1, u_2, u_3), (v_1, v_2, v_3)>$. Use the Python code to calculate the orthogonal projection of $a = (1, 0, 2)$ in $R^3$ onto $W = <(1, 1, 0), (1, 0, 1)>$.

In [ ]:
# Calculate projw(a) = p
  # projw(a) = A @ inv((A.T) @ A) @ A.T @ a
A = np.array([[1, 1], [1, 0], [0, 1]])
a = np.array([[1], [0], [2]])
p = A @ np.linalg.inv((A.T) @ A) @ A.T @ a
print(p)

[[ 1.33333333]
 [-0.33333333]
 [ 1.66666667]]


# Python problem 5.
## Let $R^4$ with the Euclidean inner product. Use the Python code to apply the Gram-Schmidt algorithm to make the orthonormal basis from the following basis $W = {(1, 1, 0, 0), (0, 1, 1, 0), (0, 0, 1, 1), (0, 0, 0, 1)}$

In [ ]:
x1 = np.array([[1, 1, 0, 0]]).T
x2 = np.array([[0, 1, 1, 0]]).T
x3 = np.array([[0, 0, 1, 1]]).T
x4 = np.array([[0, 0, 0, 1]]).T

In [ ]:
v1 = x1
v1

array([[1],
       [1],
       [0],
       [0]])

In [ ]:
# v2 = x2 - proj<v1>x2
v2 = x2 - ((x2.T @ v1) / (v1.T @ v1)) * v1
v2

array([[-0.5],
       [ 0.5],
       [ 1. ],
       [ 0. ]])

In [ ]:
# v3 = x3 - proj<v1, v2>x3
v3 = x3 - ((x3.T @ v1) / (v1.T @ v1)) * v1 -  ((x3.T @ v2) / (v2.T @ v2)) * v2
v3

array([[ 0.33333333],
       [-0.33333333],
       [ 0.33333333],
       [ 1.        ]])

In [ ]:
# v4 = x4 - proj<v1, v2, v3>x4
v4 = x4 - ((x4.T @ v1) / (v1.T @ v1)) * v1 - ((x4.T @ v2) / (v2.T @ v2)) * v2 - ((x4.T @ v3) / (v3.T @ v3)) * v3
v4

array([[-0.25],
       [ 0.25],
       [-0.25],
       [ 0.25]])

In [ ]:
# Answer
# {v1, v2, v3, v4}
v_1 = v1.reshape(1, 4)
v_2 = v2.reshape(1, 4)
v_3 = v3.reshape(1, 4)
v_4 = v4.reshape(1, 4)
print(v_1, v_2, v_3, v_4)

[[1 1 0 0]] [[-0.5  0.5  1.   0. ]] [[ 0.33333333 -0.33333333  0.33333333  1.        ]] [[-0.25  0.25 -0.25  0.25]]
